project:
  type: website
  output-dir: docs

website:
  title: "tokyo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: noodle.qmd
        text: "지바시 라멘집"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

